receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  opcua:
    endpoint: opc.tcp://localhost:4840
    security_policy: None
    security_mode: None
    auth:
      type: anonymous
    log_object_paths:
      - Objects/ServerLog
    collection_interval: 30s
    max_records_per_call: 1000

exporters:
  debug:
    verbosity: detailed
  otlp/jaeger:
    endpoint: host.docker.internal:14317
    tls:
      insecure: true
    sending_queue:
      batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger, debug]
    logs:
      receivers: [opcua]
      exporters: [debug]
  telemetry:
    logs:
      level: debug